Repository Kava-Labs/kava, pull requests merged in 2020-04, with the labels that each got.

#401 [R4R] CDP rest api automating testing
  README.md
  contrib/testnet-4000/README.md
  rest_test/run_all_tests_from_make.sh
  rest_test/setup/setuptest.go
  swagger-ui/testnet-4000/swagger-testnet-4000.yaml
Labels: R4R, cdp, enhancement, help wanted

#417 x/validator-vesting: remove internal pkg
  x/validator-vesting/abci.go
  x/validator-vesting/abci_test.go
  x/validator-vesting/alias.go
  x/validator-vesting/client/cli/query.go
  x/validator-vesting/client/rest/query.go
  x/validator-vesting/genesis.go
  x/validator-vesting/keeper/keeper.go
  x/validator-vesting/keeper/keeper_test.go
  x/validator-vesting/keeper/querier.go
  x/validator-vesting/keeper/test_common.go
  x/validator-vesting/module.go
  x/validator-vesting/simulation/decoder.go
  x/validator-vesting/simulation/genesis.go
  x/validator-vesting/test_common.go
  x/validator-vesting/types/codec.go
  x/validator-vesting/types/expected_keepers.go
  x/validator-vesting/types/genesis.go
  x/validator-vesting/types/key.go
  x/validator-vesting/types/querier.go
  x/validator-vesting/types/test_common.go
  x/validator-vesting/types/validator_vesting_account.go
  x/validator-vesting/types/validator_vesting_account_test.go
Labels: R4R, code hygiene

#412 simulation decoders for kava modules
  go.mod
  x/auction/simulation/decoder.go
  x/auction/simulation/decoder_test.go
  x/bep3/simulation/decoder.go
  x/bep3/simulation/decoder_test.go
  x/cdp/simulation/decoder.go
  x/cdp/simulation/decoder_test.go
  x/kavadist/simulation/decoder.go
  x/kavadist/simulation/decoder_test.go
  x/pricefeed/simulation/decoder.go
  x/pricefeed/simulation/decoder_test.go
  x/validator-vesting/simulation/decoder.go
  x/validator-vesting/simulation/decoder_test.go
Labels: R4R

#423 [R4R] BEP3 simulations
  app/sim_test.go
  x/bep3/simulation/genesis.go
  x/bep3/simulation/operations/msg.go
  x/bep3/simulation/params.go
Labels: R4R

#420 [R4R] Pricefeed simulations
  app/sim_test.go
  x/pricefeed/keeper/keeper.go
  x/pricefeed/simulation/genesis.go
  x/pricefeed/simulation/operations/msg.go
Labels: R4R

#419 Add Auction Simulations
  app/app.go
  app/sim_test.go
  x/auction/alias.go
  x/auction/genesis.go
  x/auction/genesis_test.go
  x/auction/keeper/auctions.go
  x/auction/keeper/invariants.go
  x/auction/module.go
  x/auction/simulation/genesis.go
  x/auction/simulation/operations/msg.go
  x/auction/simulation/params.go
  x/auction/types/auctions.go
Labels: R4R

#427 [R4R] Remove non-determinism from bep3 sims
  x/bep3/simulation/genesis.go
  x/bep3/simulation/operations/msg.go
Labels: R4R

#422 [R4R] Add cdp simulations
  app/app.go
  app/sim_test.go
  simulations/README.md
  x/cdp/simulation/genesis.go
  x/cdp/simulation/operations/msgs.go
  x/cdp/simulation/operations/utils.go
  x/cdp/simulation/operations/utils_test.go
  x/cdp/simulation/params.go
  x/pricefeed/simulation/genesis.go
Labels: R4R

#432 [R4R] fix: non-determinism in auction sims
  x/auction/simulation/operations/msg.go
Labels: bug

#436 [R4R] Pricefeed fix new version - using multiplication, does not degrade to zero
  x/pricefeed/simulation/operations/msg.go
  x/pricefeed/simulation/operations/pricegen_test.go
Labels: R4R, bug, code hygiene, enhancement

#433 [R4R] Fix: Check debt limit when adding cdp
  x/cdp/keeper/cdp.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/querier_test.go
  x/cdp/simulation/genesis.go
  x/cdp/simulation/operations/msgs.go
Labels: R4R, bug

#438 [R4R] Fix: prevent cdp sim from attempting to draw too much debt
  x/cdp/simulation/operations/msgs.go
Labels: R4R, bug

#441 [R4R]: Avoid divide by zero when price is very small
  x/cdp/keeper/fees.go
  x/cdp/keeper/seize.go
Labels: R4R, bug

#443 [R4R] Fix pricefeed non-determinism
  app/sim_test.go
  x/pricefeed/simulation/operations/msg.go
Labels: R4R

#444 [R4R] Update pricefeed sims genesis
  x/cdp/keeper/fees.go
  x/cdp/keeper/seize.go
  x/pricefeed/simulation/genesis.go
Labels: R4R, enhancement

#442 [R4R] Bep3 sim changes
  x/bep3/simulation/genesis.go
  x/bep3/simulation/operations/msg.go
Labels: R4R

#434 [R4R] Fix pricefeed sims so does not always go to zero
  app/sim_test.go
  x/cdp/simulation/operations/msgs.go
  x/pricefeed/simulation/genesis.go
  x/pricefeed/simulation/operations/msg.go
Labels: R4R, bug

#440 [R4R] Update sim tooling
  Makefile
  app/sim_test.go
Labels: R4R, code hygiene

#428 [R4R] Pricefeed cleanup
  x/pricefeed/alias.go
  x/pricefeed/genesis.go
  x/pricefeed/keeper/keeper.go
  x/pricefeed/keeper/keeper_test.go
  x/pricefeed/keeper/querier.go
  x/pricefeed/types/key.go
  x/pricefeed/types/market.go
Labels: R4R, code hygiene

#451 [WIP] Fix BEP3 module future operations
  x/bep3/simulation/operations.go
Labels: WIP

#454 [R4R] Add MsgRefundAtomicSwap future op to BEP3 sims
  x/bep3/simulation/operations.go
Labels: R4R

#450 [R4R] BEP3 module spec and clean up
  Makefile
  x/auction/simulation/operations.go
  x/bep3/alias.go
  x/bep3/keeper/swap.go
  x/bep3/keeper/swap_test.go
  x/bep3/spec/01_concepts.md
  x/bep3/spec/02_state.md
  x/bep3/spec/03_messages.md
  x/bep3/spec/04_events.md
  x/bep3/spec/05_params.md
  x/bep3/spec/06_begin_block.md
  x/bep3/spec/README.md
  x/bep3/spec/diagrams/BEP3_binance_chain_to_kava.jpg
  x/bep3/spec/diagrams/BEP3_kava_to_binance_chain.jpg
  x/bep3/types/codec.go
  x/bep3/types/common_test.go
  x/bep3/types/events.go
  x/bep3/types/swap.go
  x/bep3/types/swap_test.go
Labels: R4R

#449 [R4R] Update fees for all cdps
  x/cdp/abci.go
  x/cdp/abci_test.go
  x/cdp/alias.go
  x/cdp/genesis.go
  x/cdp/integration_test.go
  x/cdp/keeper/deposit.go
  x/cdp/keeper/draw.go
  x/cdp/keeper/draw_test.go
  x/cdp/keeper/fees.go
  x/cdp/keeper/fees_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/seize.go
  x/cdp/keeper/seize_test.go
  x/cdp/simulation/decoder.go
  x/cdp/simulation/decoder_test.go
  x/cdp/simulation/genesis.go
  x/cdp/types/genesis.go
  x/cdp/types/keys.go
  x/cdp/types/params.go
Labels: WIP, cdp, enhancement, question

#399 [R4R] USDX incentives implementation
  app/app.go
  app/test_common.go
  go.sum
  x/bep3/client/rest/query.go
  x/incentive/abci.go
  x/incentive/alias.go
  x/incentive/client/cli/query.go
  x/incentive/client/cli/tx.go
  x/incentive/client/rest/query.go
  x/incentive/client/rest/rest.go
  x/incentive/client/rest/tx.go
  x/incentive/doc.go
  x/incentive/genesis.go
  x/incentive/handler.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/params.go
  x/incentive/keeper/payout.go
  x/incentive/keeper/querier.go
  x/incentive/keeper/rewards.go
  x/incentive/module.go
  x/incentive/simulation/decoder.go
  x/incentive/simulation/params.go
  x/incentive/simulation/simulation.go
  x/incentive/types/account.go
  x/incentive/types/account_test.go
  x/incentive/types/codec.go
  x/incentive/types/errors.go
  x/incentive/types/events.go
  x/incentive/types/expected_keepers.go
  x/incentive/types/genesis.go
  x/incentive/types/keys.go
  x/incentive/types/msg.go
  x/incentive/types/msg_test.go
  x/incentive/types/params.go
  x/incentive/types/params_test.go
  x/incentive/types/period.go
  x/incentive/types/querier.go
  x/incentive/types/rewards.go
Labels: R4R

#429 [R4R] Incentives tests
  run_a_bunch_of_sims.sh
  x/incentive/handler_test.go
  x/incentive/keeper/keeper_test.go
  x/incentive/keeper/payout_test.go
  x/incentive/keeper/querier_test.go
  x/incentive/keeper/rewards_test.go
  x/incentive/types/msg_test.go
  x/incentive/types/params.go
  x/incentive/types/params_test.go
Labels: R4R

#439 [R4R] Incentive module simulations
  app/app.go
  app/params/params.go
  app/sim_test.go
  run_a_bunch_of_sims.sh
  x/cdp/simulation/genesis.go
  x/incentive/module.go
  x/incentive/simulation/decoder.go
  x/incentive/simulation/decoder_test.go
  x/incentive/simulation/genesis.go
  x/incentive/simulation/operations.go
  x/incentive/simulation/params.go
  x/incentive/simulation/simulation.go
  x/kavadist/simulation/genesis.go
Labels: R4R

#466 [R4R] Use sdk.Coin in cdp module
  rest_test/setup/setuptest.go
  x/cdp/abci.go
  x/cdp/abci_test.go
  x/cdp/alias.go
  x/cdp/client/cli/tx.go
  x/cdp/client/rest/rest.go
  x/cdp/genesis.go
  x/cdp/genesis_test.go
  x/cdp/handler.go
  x/cdp/handler_test.go
  x/cdp/integration_test.go
  x/cdp/keeper/auctions.go
  x/cdp/keeper/cdp.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/deposit.go
  x/cdp/keeper/deposit_test.go
  x/cdp/keeper/draw.go
  x/cdp/keeper/draw_test.go
  x/cdp/keeper/fees.go
  x/cdp/keeper/fees_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/keeper_bench_test.go
  x/cdp/keeper/params.go
  x/cdp/keeper/querier.go
  x/cdp/keeper/querier_test.go
  x/cdp/keeper/seize.go
  x/cdp/keeper/seize_test.go
  x/cdp/simulation/decoder_test.go
  x/cdp/simulation/genesis.go
  x/cdp/simulation/operations.go
  x/cdp/spec/01_concepts.md
  x/cdp/spec/02_state.md
  x/cdp/spec/03_messages.md
  x/cdp/spec/04_begin_block.md
  x/cdp/spec/06_params.md
  x/cdp/spec/README.md
  x/cdp/types/cdp.go
  x/cdp/types/deposit.go
  x/cdp/types/errors.go
  x/cdp/types/genesis.go
  x/cdp/types/msg.go
  x/cdp/types/msg_test.go
  x/cdp/types/params.go
  x/cdp/types/params_test.go
  x/incentive/keeper/rewards.go
  x/incentive/keeper/rewards_test.go
Labels: R4R, cdp-testnet-release

#386 Committee Gov Module
  app/app.go
  app/test_common.go
  x/committee/abci.go
  x/committee/abci_test.go
  x/committee/alias.go
  x/committee/client/cli/cli_test.go
  x/committee/client/cli/query.go
  x/committee/client/cli/tx.go
  x/committee/client/common/query_proposer.go
  x/committee/client/proposal_handler.go
  x/committee/client/rest/query.go
  x/committee/client/rest/rest.go
  x/committee/client/rest/tx.go
  x/committee/genesis.go
  x/committee/genesis_test.go
  x/committee/handler.go
  x/committee/handler_test.go
  x/committee/integration_test.go
  x/committee/keeper/integration_test.go
  x/committee/keeper/keeper.go
  x/committee/keeper/keeper_test.go
  x/committee/keeper/proposal.go
  x/committee/keeper/proposal_test.go
  x/committee/keeper/querier.go
  x/committee/keeper/querier_test.go
  x/committee/module.go
  x/committee/proposal_handler.go
  x/committee/proposal_handler_test.go
  x/committee/simulation/decoder.go
  x/committee/simulation/genesis.go
  x/committee/simulation/params.go
  x/committee/spec/README.md
  x/committee/types/codec.go
  x/committee/types/committee.go
  x/committee/types/committee_test.go
  x/committee/types/errors.go
  x/committee/types/events.go
  x/committee/types/genesis.go
  x/committee/types/genesis_test.go
  x/committee/types/keys.go
  x/committee/types/msg.go
  x/committee/types/msg_test.go
  x/committee/types/permissions.go
  x/committee/types/permissions_test.go
  x/committee/types/proposal.go
  x/committee/types/querier.go
Labels: R4R

#470 fix CLI tests
  Makefile
  cli_test/README.md
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/kvd/add_account.go
Labels: R4R
