Repository Kava-Labs/kava, pull requests merged in 2020-12, with the labels that each got.

#720 Harvest: interest rate logic
  Makefile
  x/harvest/alias.go
  x/harvest/keeper/borrow.go
  x/harvest/keeper/borrow_test.go
  x/harvest/keeper/claim_test.go
  x/harvest/keeper/deposit.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/interest.go
  x/harvest/keeper/interest_test.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/keeper_test.go
  x/harvest/keeper/params.go
  x/harvest/keeper/rewards_test.go
  x/harvest/keeper/timelock_test.go
  x/harvest/types/borrow.go
  x/harvest/types/errors.go
  x/harvest/types/keys.go
  x/harvest/types/params.go
Labels: R4R, state-machine breaking

#730 Hard: hotfix panic
  x/harvest/keeper/borrow.go
Labels: R4R

#726 Hard: repay insufficient balance error
  x/harvest/keeper/repay.go
  x/harvest/keeper/repay_test.go
  x/harvest/types/errors.go
Labels: R4R, blocked

#732 Hard: query borrow balance
  x/harvest/client/cli/query.go
  x/harvest/keeper/borrow.go
  x/harvest/keeper/querier.go
  x/harvest/types/querier.go
Labels: R4R

#725 Hard: repay borrowed coins
  x/harvest/client/cli/tx.go
  x/harvest/handler.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/repay.go
  x/harvest/keeper/repay_test.go
  x/harvest/types/codec.go
  x/harvest/types/errors.go
  x/harvest/types/events.go
  x/harvest/types/msg.go
  x/harvest/types/msg_test.go
Labels: R4R

#733 Hard: update LTV error msg
  x/harvest/keeper/borrow.go
  x/harvest/keeper/borrow_test.go
  x/harvest/types/errors.go
Labels: R4R

#731 Hard: liquidation by keeper
  app/app.go
  x/harvest/alias.go
  x/harvest/client/cli/tx.go
  x/harvest/genesis.go
  x/harvest/keeper/borrow_test.go
  x/harvest/keeper/claim_test.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/interest_test.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/keeper_test.go
  x/harvest/keeper/liquidation.go
  x/harvest/keeper/liquidation_test.go
  x/harvest/keeper/repay_test.go
  x/harvest/keeper/rewards_test.go
  x/harvest/keeper/timelock_test.go
  x/harvest/types/codec.go
  x/harvest/types/errors.go
  x/harvest/types/events.go
  x/harvest/types/expected_keepers.go
  x/harvest/types/keys.go
  x/harvest/types/liquidation.go
  x/harvest/types/msg.go
  x/harvest/types/params.go
  x/harvest/types/params_test.go
Labels: R4R

#742 Hard: introduce LTV index
  x/harvest/keeper/borrow.go
  x/harvest/keeper/borrow_test.go
  x/harvest/keeper/deposit.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/keeper_test.go
  x/harvest/keeper/liquidation.go
  x/harvest/keeper/repay.go
  x/harvest/keeper/repay_test.go
  x/harvest/types/errors.go
  x/harvest/types/keys.go
Labels: R4R

#743 Hard: automatic liquidation by LTV index
  x/harvest/abci.go
  x/harvest/keeper/borrow.go
  x/harvest/keeper/borrow_test.go
  x/harvest/keeper/claim_test.go
  x/harvest/keeper/deposit.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/interest_test.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/keeper_test.go
  x/harvest/keeper/liquidation.go
  x/harvest/keeper/liquidation_test.go
  x/harvest/keeper/repay.go
  x/harvest/keeper/repay_test.go
  x/harvest/keeper/rewards_test.go
  x/harvest/keeper/timelock_test.go
  x/harvest/types/genesis_test.go
  x/harvest/types/params.go
  x/harvest/types/params_test.go
Labels: R4R

#744 [hard] Update deposit type to use sdk.Coins
  x/harvest/alias.go
  x/harvest/client/cli/tx.go
  x/harvest/client/rest/rest.go
  x/harvest/keeper/borrow.go
  x/harvest/keeper/borrow_test.go
  x/harvest/keeper/deposit.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/interest_test.go
  x/harvest/keeper/keeper.go
  x/harvest/keeper/keeper_test.go
  x/harvest/keeper/liquidation.go
  x/harvest/keeper/liquidation_test.go
  x/harvest/keeper/querier.go
  x/harvest/keeper/repay_test.go
  x/harvest/keeper/rewards.go
  x/harvest/keeper/rewards_test.go
  x/harvest/simulation/decoder_test.go
  x/harvest/types/deposit.go
  x/harvest/types/errors.go
  x/harvest/types/keys.go
  x/harvest/types/msg.go
  x/harvest/types/msg_test.go
Labels: R4R

#745 Hard: update accumulator name to 'InterestFactor'
  x/harvest/keeper/borrow.go
  x/harvest/keeper/interest.go
  x/harvest/keeper/interest_test.go
  x/harvest/keeper/keeper.go
  x/harvest/types/borrow.go
  x/harvest/types/keys.go
Labels: R4R

#747 Hard: withdraws limited by ltv
  x/hard/genesis.go
  x/hard/keeper/deposit.go
  x/hard/keeper/deposit_test.go
  x/hard/keeper/liquidation.go
  x/hard/keeper/liquidation_test.go
Labels: R4R

#748 Hard: update REST API
  x/hard/client/cli/query.go
  x/hard/client/rest/query.go
  x/hard/client/rest/rest.go
  x/hard/client/rest/tx.go
  x/hard/handler.go
  x/hard/keeper/querier.go
  x/hard/types/msg.go
  x/hard/types/querier.go
Labels: R4R
