Repository Kava-Labs/kava, pull requests merged in 2020-01, with the labels that each got.

#276 Update Auction Module
  app/app.go
  app/test_common.go
  x/auction/abci.go
  x/auction/abci_test.go
  x/auction/alias.go
  x/auction/client/cli/tx.go
  x/auction/client/rest/tx.go
  x/auction/doc.go
  x/auction/genesis.go
  x/auction/handler.go
  x/auction/keeper/auctions.go
  x/auction/keeper/auctions_test.go
  x/auction/keeper/integration_test.go
  x/auction/keeper/keeper.go
  x/auction/keeper/keeper_test.go
  x/auction/keeper/math.go
  x/auction/keeper/math_test.go
  x/auction/keeper/params.go
  x/auction/keeper/querier.go
  x/auction/module.go
  x/auction/spec/01_concepts.md
  x/auction/spec/02_state.md
  x/auction/spec/03_messages.md
  x/auction/spec/04_events.md
  x/auction/spec/05_params.md
  x/auction/spec/06_end_block.md
  x/auction/spec/README.md
  x/auction/types/auctions.go
  x/auction/types/auctions_test.go
  x/auction/types/codec.go
  x/auction/types/expected_keepers.go
  x/auction/types/genesis.go
  x/auction/types/keys.go
  x/auction/types/msg.go
  x/auction/types/msg_test.go
  x/auction/types/params.go
  x/auction/types/params_test.go
  x/auction/types/querier.go
  x/auction/types/utils.go
  x/liquidator/keeper/keeper.go
  x/liquidator/types/expected_keepers.go
Labels: R4R

#281 Various Auction TODOs
  app/app.go
  x/auction/alias.go
  x/auction/genesis.go
  x/auction/genesis_test.go
  x/auction/handler.go
  x/auction/keeper/auctions.go
  x/auction/keeper/auctions_test.go
  x/auction/module.go
  x/auction/spec/04_events.md
  x/auction/types/auctions.go
  x/auction/types/codec.go
  x/auction/types/events.go
  x/auction/types/genesis.go
  x/auction/types/genesis_test.go
Labels: R4R

#283 [R4R] Auction module tests code coverage
  x/auction/keeper/auctions.go
  x/auction/keeper/auctions_test.go
  x/auction/keeper/bidding_test.go
  x/auction/keeper/querier.go
  x/auction/keeper/querier_test.go
  x/auction/types/auctions.go
  x/auction/types/auctions_test.go
  x/auction/types/keys.go
  x/auction/types/querier.go
Labels: R4R

#285 [R4R] Custom sdk.Error types for the auction module
  x/auction/alias.go
  x/auction/handler.go
  x/auction/keeper/auctions.go
  x/auction/keeper/bidding_test.go
  x/auction/keeper/keeper.go
  x/auction/keeper/querier.go
  x/auction/types/errors.go
  x/auction/types/msg.go
Labels: R4R, cdp

#280 R4R: Move liquidator functions to cdp module
  .gitignore
  app/app.go
  app/test_common.go
  x/auction/keeper/keeper.go
  x/auction/types/expected_keepers.go
  x/cdp/abci.go
  x/cdp/abci_test.go
  x/cdp/alias.go
  x/cdp/client/cli/query.go
  x/cdp/genesis.go
  x/cdp/integration_test.go
  x/cdp/keeper/auctions.go
  x/cdp/keeper/auctions_test.go
  x/cdp/keeper/cdp.go
  x/cdp/keeper/deposit.go
  x/cdp/keeper/deposit_test.go
  x/cdp/keeper/draw.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/keeper.go
  x/cdp/keeper/params.go
  x/cdp/keeper/seize.go
  x/cdp/keeper/seize_test.go
  x/cdp/types/deposit.go
  x/cdp/types/events.go
  x/cdp/types/expected_keepers.go
  x/cdp/types/genesis.go
  x/cdp/types/keys.go
  x/cdp/types/keys_test.go
  x/cdp/types/params.go
Labels: R4R, cdp

#305 cdp cli clean up
  x/cdp/client/cli/query.go
  x/cdp/client/cli/tx.go
  x/cdp/keeper/querier.go
  x/cdp/types/params.go
  x/cdp/types/querier.go
Labels: R4R

#307 Add stability fee validation
  x/cdp/types/params.go
Labels: R4R

#310 R4R: cli auction clean up
  x/auction/client/cli/query.go
  x/auction/client/cli/tx.go
  x/auction/client/rest/query.go
  x/auction/keeper/querier.go
  x/auction/types/querier.go
Labels: R4R, cdp-testnet-release

#311 R4R: add params query to pricefeed module
  x/pricefeed/client/cli/query.go
  x/pricefeed/client/cli/tx.go
  x/pricefeed/client/rest/query.go
  x/pricefeed/keeper/querier.go
  x/pricefeed/types/codec.go
  x/pricefeed/types/errors.go
  x/pricefeed/types/msgs_test.go
  x/pricefeed/types/querier.go
Labels: R4R, blocked, cdp-testnet-release

#325 clean orphaned MsgTransferCDP from CDP module
  x/cdp/alias.go
  x/cdp/types/codec.go
  x/cdp/types/msg.go
Labels: R4R, cdp-testnet-release

#328 Add CDP Spec
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
  x/auction/spec/04_events.md
  x/auction/spec/README.md
  x/cdp/spec/01_concepts.md
  x/cdp/spec/02_state.md
  x/cdp/spec/03_messages.md
  x/cdp/spec/04_begin_block.md
  x/cdp/spec/05_events.md
  x/cdp/spec/06_params.md
  x/cdp/spec/README.md
Labels: R4R

#331 [WIP] example proposal.json files for param changes
  contrib/genesis_examples/genesis_test_collateral_auctions.json
  contrib/genesis_examples/genesis_test_debt_auctions.json
  contrib/proposal_examples/addcollateral/addcollateral.json
  contrib/proposal_examples/addcollateral/addcollateral2.json
  contrib/proposal_examples/addcollateral/genesis_addcollateral.json
  contrib/proposal_examples/addmarket/addmarket.json
  contrib/proposal_examples/addmarket/genesis_addmarket.json
  contrib/proposal_examples/updatebidduration/updatebidduration.json
  contrib/proposal_examples/updatedebtlimit/genesis_updatedebtlimit.json
  contrib/proposal_examples/updatedebtlimit/updatedebtlimit.json
  contrib/proposal_examples/updatemaxauctionduration/updatemaxauctionduration.json
Labels: WIP

#347 R4R: add collateral value, collateralization ratio to CDP querier
  x/cdp/alias.go
  x/cdp/client/cli/query.go
  x/cdp/keeper/cdp.go
  x/cdp/keeper/querier.go
  x/cdp/keeper/querier_test.go
  x/cdp/types/cdp.go
  x/cdp/types/errors.go
Labels: R4R, cdp-testnet-release

#352 R4R fix posted prices in genesis file
  x/pricefeed/genesis.go
Labels: R4R, bug, cdp-testnet-release

#353 R4R: Avoid panic when closing a single cdp via repayment
  x/cdp/keeper/cdp.go
  x/cdp/keeper/draw.go
Labels: R4R, cdp-testnet-release
