Repository Kava-Labs/kava, pull requests merged in 2020-03, with the labels that each got.

#381 [R4R] Update fees risky cdps
  x/cdp/abci.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/fees.go
  x/cdp/keeper/fees_test.go
  x/cdp/keeper/seize.go
  x/cdp/spec/04_begin_block.md
  x/cdp/types/cdp.go
Labels: R4R, cdp, enhancement

#365 [R4R] Add Savings Rate
  app/app.go
  contrib/genesis_examples/genesis_savings_rate.json
  x/cdp/abci.go
  x/cdp/alias.go
  x/cdp/genesis.go
  x/cdp/integration_test.go
  x/cdp/keeper/auctions.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/keeper.go
  x/cdp/keeper/savings.go
  x/cdp/keeper/savings_test.go
  x/cdp/keeper/seize.go
  x/cdp/module.go
  x/cdp/spec/04_begin_block.md
  x/cdp/spec/06_params.md
  x/cdp/types/expected_keepers.go
  x/cdp/types/genesis.go
  x/cdp/types/keys.go
  x/cdp/types/params.go
Labels: R4R, cdp

#388 R4R: bep3 module upgrades
  contrib/testnet-5000/genesis_examples/genesis_bep3.json
  x/bep3/client/cli/query.go
  x/bep3/client/cli/tx.go
  x/bep3/client/rest/tx.go
  x/bep3/keeper/common_test.go
  x/bep3/keeper/keeper_test.go
  x/bep3/keeper/swap.go
  x/bep3/types/swap.go
Labels: R4R

#387 [R4R] Kava distribution module
  app/app.go
  app/test_common.go
  x/kavadist/abci.go
  x/kavadist/alias.go
  x/kavadist/doc.go
  x/kavadist/genesis.go
  x/kavadist/handler.go
  x/kavadist/keeper/keeper.go
  x/kavadist/keeper/mint.go
  x/kavadist/keeper/mint_test.go
  x/kavadist/keeper/params.go
  x/kavadist/module.go
  x/kavadist/simulation/decoder.go
  x/kavadist/simulation/params.go
  x/kavadist/simulation/simulation.go
  x/kavadist/types/codec.go
  x/kavadist/types/errors.go
  x/kavadist/types/events.go
  x/kavadist/types/expected_keepers.go
  x/kavadist/types/genesis.go
  x/kavadist/types/keys.go
  x/kavadist/types/params.go
  x/kavadist/types/params_test.go
  x/kavadist/types/querier.go
Labels: R4R

#394 [R4R] fix: update genesis for guide
  contrib/testnet-5000/genesis_examples/genesis_bep3.json
Labels: R4R, bug

#395 R4R: BEP3 module test suite
  x/bep3/abci.go
  x/bep3/client/cli/tx.go
  x/bep3/keeper/asset_test.go
  x/bep3/keeper/common_test.go
  x/bep3/keeper/integration_test.go
  x/bep3/keeper/keeper_test.go
  x/bep3/keeper/params_test.go
  x/bep3/keeper/querier_test.go
  x/bep3/keeper/swap.go
  x/bep3/keeper/swap_test.go
  x/bep3/module.go
  x/bep3/types/common_test.go
  x/bep3/types/errors.go
  x/bep3/types/genesis.go
  x/bep3/types/genesis_test.go
  x/bep3/types/hash.go
  x/bep3/types/hash_test.go
  x/bep3/types/msg.go
  x/bep3/types/msg_test.go
  x/bep3/types/params.go
  x/bep3/types/params_test.go
  x/bep3/types/querier.go
  x/bep3/types/swap_test.go
Labels: R4R

#397 R4R: BEP3 additional features + module test suite
  contrib/testnet-5000/genesis_examples/bep3_genesis.json
  x/bep3/abci.go
  x/bep3/abci_test.go
  x/bep3/alias.go
  x/bep3/client/cli/query.go
  x/bep3/genesis.go
  x/bep3/genesis_test.go
  x/bep3/handler.go
  x/bep3/handler_test.go
  x/bep3/integration_test.go
  x/bep3/keeper/asset.go
  x/bep3/keeper/asset_test.go
  x/bep3/keeper/integration_test.go
  x/bep3/keeper/keeper.go
  x/bep3/keeper/keeper_test.go
  x/bep3/keeper/params.go
  x/bep3/keeper/params_test.go
  x/bep3/keeper/querier.go
  x/bep3/keeper/querier_test.go
  x/bep3/keeper/swap.go
  x/bep3/keeper/swap_test.go
  x/bep3/module.go
  x/bep3/types/asset.go
  x/bep3/types/common_test.go
  x/bep3/types/errors.go
  x/bep3/types/events.go
  x/bep3/types/genesis.go
  x/bep3/types/genesis_test.go
  x/bep3/types/hash.go
  x/bep3/types/keys.go
  x/bep3/types/msg.go
  x/bep3/types/params.go
  x/bep3/types/params_test.go
  x/bep3/types/querier.go
  x/bep3/types/swap.go
  x/bep3/types/swap_test.go
Labels: R4R

#390 [R4R] Swagger Rest Automating Testing
  Makefile
  go.mod
  rest_test/how_to_run_dredd_tests.md
  rest_test/run_all_tests_from_make.sh
  rest_test/setup/setuptest.go
  rest_test/stopchain.sh
  swagger-ui/swagger.yaml
Labels: R4R, enhancement

#402 R4R: Update BEP3 rest endpoints + format example requests
  contrib/testnet-5000/README.md
  contrib/testnet-5000/rest_examples/broadcast-claim-swap.json
  contrib/testnet-5000/rest_examples/broadcast-create-swap.json
  contrib/testnet-5000/rest_examples/broadcast-refund-swap.json
  contrib/testnet-5000/rest_examples/claim-swap-unsigned.json
  contrib/testnet-5000/rest_examples/claim-swap.json
  contrib/testnet-5000/rest_examples/create-swap-unsigned.json
  contrib/testnet-5000/rest_examples/create-swap.json
  contrib/testnet-5000/rest_examples/refund-swap-unsigned.json
  contrib/testnet-5000/rest_examples/refund-swap.json
  x/bep3/client/cli/query.go
  x/bep3/client/cli/tx.go
  x/bep3/client/rest/query.go
  x/bep3/client/rest/rest.go
  x/bep3/client/rest/tx.go
  x/bep3/types/querier.go
Labels: R4R

#403 R4R: organize contrib folder
  contrib/README.md
  contrib/dev/genesis_examples/genesis_savings_rate.json
  contrib/testnet-4000/README.md
  contrib/testnet-4000/rest_examples/cdp/broadcast-create-cdp.json
  contrib/testnet-4000/rest_examples/cdp/broadcast-deposit-cdp.json
  contrib/testnet-4000/rest_examples/cdp/create-cdp-unsigned.json
  contrib/testnet-4000/rest_examples/cdp/create-cdp.json
  contrib/testnet-4000/rest_examples/cdp/deposit-cdp.json
  contrib/testnet-4000/rest_examples/cdp/example-create-cdp.json
  contrib/testnet-4000/rest_examples/pricefeed/broadcast-post-price.json
  contrib/testnet-4000/rest_examples/pricefeed/example-post-price.json
  contrib/testnet-4000/rest_examples/pricefeed/post-price-unsigned.json
  contrib/testnet-4000/rest_examples/pricefeed/post-price.json
  contrib/testnet-5000/README.md
Labels: R4R, enhancement

#408 Add simulation stubs to bep3 make tests pass
  app/app.go
  x/bep3/module.go
  x/bep3/simulation/decoder.go
  x/bep3/simulation/genesis.go
  x/bep3/simulation/params.go
Labels: R4R

#410 Update README to new logo
  README.md
  kava-logo.svg
Labels: R4R

#411 [R4R] fix: add auction begin blocker [HOTFIX]
  app/app.go
Labels: R4R
