Repository Kava-Labs/kava, pull requests merged in 2020-05, with the labels that each got.

#431 Add committee simulations
  app/params/params.go
  app/sim_test.go
  x/committee/alias.go
  x/committee/keeper/invariants.go
  x/committee/module.go
  x/committee/simulation/common.go
  x/committee/simulation/decoder.go
  x/committee/simulation/decoder_test.go
  x/committee/simulation/genesis.go
  x/committee/simulation/operations.go
  x/committee/simulation/params.go
  x/committee/simulation/proposals.go
  x/committee/types/committee.go
  x/committee/types/genesis.go
Labels: R4R

#486 Fix #463, add-genesis-account command for v0.38
  cmd/kvd/add_account.go
Labels: R4R

#464 [R4R] fixing dredd tests for bump to v38 of sdk
  rest_test/run_all_tests_from_make.sh
  rest_test/setup/setuptest.go
  swagger-ui/testnet-4000/swagger-testnet-4000.yaml
Labels: R4R

#477 Update keys add cmd patch
  cli_test/cli_test.go
  cmd/kvcli/cmd_keys.go
Labels: R4R

#482 [R4R] Enable bep3 claim txs from new addresses
  app/app.go
  x/bep3/alias.go
  x/bep3/genesis.go
  x/bep3/keeper/keeper.go
  x/bep3/keeper/swap.go
  x/bep3/module.go
  x/bep3/simulation/operations.go
  x/bep3/types/expected_keepers.go
Labels: R4R, enhancement

#484 [R4R] Add outgoing swaps to bep3 sims
  x/bep3/simulation/operations.go
Labels: R4R, sims

#483 [R4R] Update bep3 module account permissions
  app/app.go
  x/bep3/genesis.go
  x/bep3/keeper/keeper.go
  x/bep3/types/expected_keepers.go
Labels: R4R

#490 [HOTFIX] Fix outgoing swaps in BEP3 sims
  x/bep3/simulation/operations.go
Labels: R4R, bug, sims

#493 app: upgrade module
  app/app.go
  app/app_test.go
  app/sim_test.go
  app/test_common.go
  cmd/kvd/main.go
Labels: R4R

#488 x/bep3: genesis validation
  x/bep3/genesis_test.go
  x/bep3/integration_test.go
  x/bep3/types/asset.go
  x/bep3/types/asset_test.go
  x/bep3/types/common_test.go
  x/bep3/types/genesis.go
  x/bep3/types/genesis_test.go
  x/bep3/types/swap.go
  x/bep3/types/swap_test.go
Labels: R4R

#507 x/bep3: fix swap validation
  x/bep3/simulation/genesis.go
  x/bep3/types/swap.go
  x/bep3/types/swap_test.go
Labels: R4R

#497 Auction audit revisions
  x/auction/alias.go
  x/auction/genesis_test.go
  x/auction/keeper/auctions.go
  x/auction/keeper/keeper.go
  x/auction/keeper/math.go
  x/auction/keeper/math_test.go
  x/auction/spec/04_events.md
  x/auction/types/auctions.go
  x/auction/types/auctions_test.go
  x/auction/types/errors.go
  x/auction/types/events.go
  x/auction/types/genesis.go
  x/auction/types/msg_test.go
  x/auction/types/params_test.go
  x/cdp/keeper/auctions.go
  x/cdp/keeper/seize.go
Labels: R4R

#509 [R4R] Update secure RNG to generate bytes directly
  x/bep3/client/cli/query.go
  x/bep3/client/cli/tx.go
  x/bep3/keeper/swap.go
  x/bep3/types/hash.go
  x/bep3/types/hash_test.go
Labels: R4R

#510 Committtee audit revisions
  app/app.go
  contrib/testnet-6000/genesis_examples/proposal_examples/committee_change_proposal.json
  contrib/testnet-6000/genesis_examples/proposal_examples/upgrade_proposal.json
  x/committee/abci.go
  x/committee/abci_test.go
  x/committee/alias.go
  x/committee/client/cli/tx.go
  x/committee/handler.go
  x/committee/handler_test.go
  x/committee/keeper/committee_test.go
  x/committee/keeper/invariants.go
  x/committee/keeper/keeper.go
  x/committee/keeper/param_permission_test.go
  x/committee/keeper/proposal.go
  x/committee/keeper/proposal_test.go
  x/committee/proposal_handler.go
  x/committee/simulation/genesis.go
  x/committee/simulation/operations.go
  x/committee/simulation/proposals.go
  x/committee/spec/04_events.md
  x/committee/types/codec.go
  x/committee/types/committee.go
  x/committee/types/expected_keepers.go
  x/committee/types/genesis.go
  x/committee/types/genesis_test.go
  x/committee/types/param_permissions_test.go
  x/committee/types/permissions.go
  x/committee/types/permissions_test.go
Labels: R4R

#512 [R4R] Change AssetSupply increment from !GTE to LT
  x/bep3/keeper/asset.go
Labels: R4R

#514 x/pricefeed: GenesisState validation
  x/pricefeed/genesis.go
  x/pricefeed/types/genesis.go
  x/pricefeed/types/genesis_test.go
  x/pricefeed/types/market.go
  x/pricefeed/types/market_test.go
  x/pricefeed/types/params.go
Labels: R4R

#517 [R4R] Blacklist module accounts
  app/app.go
  app/app_test.go
  x/bep3/handler.go
  x/bep3/keeper/keeper.go
  x/bep3/keeper/swap.go
  x/bep3/keeper/swap_test.go
  x/cdp/keeper/keeper.go
  x/cdp/keeper/savings.go
Labels: R4R

#500 x/auction: types validation
  x/auction/types/auctions.go
  x/auction/types/auctions_test.go
  x/auction/types/msg.go
  x/auction/types/msg_test.go
  x/incentive/types/genesis.go
  x/incentive/types/msg.go
  x/validator-vesting/types/genesis.go
Labels: R4R

#524 [R4R] Add liquidation pricefeed
  x/cdp/abci.go
  x/cdp/genesis.go
  x/cdp/integration_test.go
  x/cdp/keeper/cdp.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/deposit.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/params.go
  x/cdp/keeper/querier.go
  x/cdp/keeper/querier_test.go
  x/cdp/simulation/genesis.go
  x/cdp/simulation/operations.go
  x/cdp/spec/01_concepts.md
  x/cdp/spec/06_params.md
  x/cdp/types/params.go
  x/cdp/types/params_test.go
  x/committee/keeper/param_permission_test.go
  x/committee/keeper/proposal_test.go
  x/committee/types/param_permissions_test.go
  x/committee/types/permissions.go
  x/incentive/keeper/rewards_test.go
Labels: R4R

#523 REST Client Cleanup & Validation
  x/cdp/client/rest/query.go
  x/cdp/client/rest/tx.go
  x/incentive/client/rest/query.go
  x/incentive/client/rest/tx.go
Labels: R4R

#522 [R4R] Add flags to auction queries
  x/auction/client/cli/query.go
  x/auction/client/rest/query.go
  x/auction/client/rest/rest.go
  x/auction/client/rest/tx.go
  x/auction/keeper/keeper.go
  x/auction/keeper/querier.go
  x/auction/keeper/querier_test.go
  x/auction/types/auctions.go
  x/auction/types/querier.go
  x/bep3/keeper/querier.go
Labels: R4R

#519 x/incentive: genesis validation
  x/incentive/simulation/genesis.go
  x/incentive/types/genesis.go
  x/incentive/types/genesis_test.go
  x/incentive/types/params.go
  x/incentive/types/params_test.go
  x/incentive/types/rewards.go
  x/incentive/types/rewards_test.go
Labels: R4R

#530 Documentation website
  .gitignore
  docs/.vuepress/config.js
  docs/.vuepress/public/favicon.ico
  docs/.vuepress/public/kava-logo.svg
  docs/.vuepress/styles/index.styl
  docs/package-lock.json
  docs/package.json
  docs/post.sh
  docs/pre.sh
  docs/readme.md
Labels: R4R

#532 Fix expiry parsing
  x/pricefeed/alias.go
  x/pricefeed/client/cli/tx.go
  x/pricefeed/client/rest/tx.go
  x/pricefeed/types/msgs.go
Labels: R4R

#531 [R4R] Add surplus and debt auction lot params
  x/cdp/alias.go
  x/cdp/integration_test.go
  x/cdp/keeper/auctions.go
  x/cdp/keeper/auctions_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/simulation/genesis.go
  x/cdp/spec/06_params.md
  x/cdp/types/params.go
  x/cdp/types/params_test.go
  x/incentive/keeper/rewards_test.go
Labels: R4R
