Repository Kava-Labs/kava, pull requests merged in 2021-01, with the labels that each got.

#750 Add cdp liquidations by external keeper
  migrate/v0_13/migrate.go
  x/auction/types/auctions.go
  x/cdp/abci.go
  x/cdp/alias.go
  x/cdp/client/cli/tx.go
  x/cdp/client/rest/rest.go
  x/cdp/client/rest/tx.go
  x/cdp/handler.go
  x/cdp/integration_test.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/interest.go
  x/cdp/keeper/interest_test.go
  x/cdp/keeper/keeper.go
  x/cdp/keeper/seize.go
  x/cdp/keeper/seize_test.go
  x/cdp/legacy/v0_13/types.go
  x/cdp/types/errors.go
  x/cdp/types/msg.go
  x/cdp/types/params.go
  x/cdp/types/params_test.go
Labels: R4R

#749 Hard: suppliers earn interest
  x/hard/alias.go
  x/hard/keeper/borrow.go
  x/hard/keeper/deposit.go
  x/hard/keeper/deposit_test.go
  x/hard/keeper/interest.go
  x/hard/keeper/interest_test.go
  x/hard/keeper/keeper.go
  x/hard/keeper/keeper_test.go
  x/hard/keeper/liquidation.go
  x/hard/keeper/repay.go
  x/hard/keeper/repay_test.go
  x/hard/keeper/rewards_test.go
  x/hard/keeper/withdraw.go
  x/hard/keeper/withdraw_test.go
  x/hard/simulation/decoder_test.go
  x/hard/types/borrow.go
  x/hard/types/deposit.go
  x/hard/types/errors.go
  x/hard/types/keys.go
Labels: R4R

#759 Supply-side interest acceptance criteria
  x/hard/client/cli/query.go
  x/hard/client/rest/query.go
  x/hard/keeper/deposit.go
  x/hard/keeper/querier.go
  x/hard/types/querier.go
Labels: R4R

#758 Hard: LTV index refactor
  x/hard/handler.go
  x/hard/keeper/borrow.go
  x/hard/keeper/deposit.go
  x/hard/keeper/liquidation.go
  x/hard/keeper/liquidation_test.go
  x/hard/keeper/repay.go
  x/hard/keeper/withdraw.go
Labels: R4R

#760 Hard: fix example CLI liquidate cmd
  x/hard/client/cli/tx.go
Labels: R4R, documentation

#762 Hard: investigate sdk.RelativePow runtime panic
  x/hard/keeper/interest_test.go
Labels: R4R

#763 Hard: sync supply interest on attempted liquidation
  x/hard/keeper/liquidation.go
  x/hard/keeper/liquidation_test.go
Labels: R4R

#761 Hard: refactor borrow/borrows and deposit/deposits query
  x/hard/alias.go
  x/hard/client/cli/query.go
  x/hard/client/rest/query.go
  x/hard/client/rest/rest.go
  x/hard/keeper/borrow.go
  x/hard/keeper/deposit.go
  x/hard/keeper/querier.go
  x/hard/types/borrow.go
  x/hard/types/deposit.go
  x/hard/types/querier.go
Labels: R4R

#767 Docs Link Fix
  docs/.vuepress/config.js
Labels: R4R

#764 Remove savings rate
  app/app.go
  migrate/v0_11/migrate.go
  migrate/v0_13/migrate.go
  migrate/v0_13/testdata/kava-4-cdp-state-block-500000.json
  x/cdp/abci.go
  x/cdp/alias.go
  x/cdp/client/cli/query.go
  x/cdp/client/rest/query.go
  x/cdp/genesis.go
  x/cdp/genesis_test.go
  x/cdp/integration_test.go
  x/cdp/keeper/cdp_test.go
  x/cdp/keeper/integration_test.go
  x/cdp/keeper/interest.go
  x/cdp/keeper/keeper.go
  x/cdp/keeper/keeper_test.go
  x/cdp/keeper/querier.go
  x/cdp/keeper/querier_test.go
  x/cdp/keeper/savings.go
  x/cdp/keeper/savings_test.go
  x/cdp/legacy/v0_11/types.go
  x/cdp/legacy/v0_13/types.go
  x/cdp/legacy/v0_9/types.go
  x/cdp/simulation/decoder.go
  x/cdp/simulation/decoder_test.go
  x/cdp/simulation/genesis.go
  x/cdp/types/genesis.go
  x/cdp/types/keys.go
  x/cdp/types/params.go
  x/cdp/types/params_test.go
  x/committee/keeper/param_permission_test.go
  x/committee/legacy/v0_11/types.go
  x/committee/legacy/v0_9/types.go
  x/committee/types/param_permissions_test.go
  x/committee/types/permissions.go
  x/incentive/keeper/integration_test.go
Labels: R4R

#766 Hard: delete borrow/deposit from store on 0 amount
  x/hard/keeper/liquidation.go
  x/hard/keeper/repay_test.go
  x/hard/keeper/withdraw_test.go
Labels: R4R, bug

#765 Add usdx incentives calculation test
  x/incentive/keeper/integration_test.go
  x/incentive/keeper/rewards.go
  x/incentive/keeper/rewards_test.go
  x/incentive/types/expected_keepers.go
Labels: R4R

#770 [R4R] fix: validate usdx minting collaterals in incentive genesis
  app/app.go
  x/incentive/genesis.go
  x/incentive/handler_test.go
  x/incentive/integration_test.go
  x/incentive/module.go
  x/incentive/types/expected_keepers.go
Labels: R4R

#756 Hard: incentive rewards PR #1
  app/app.go
  migrate/v0_11/migrate.go
  x/hard/abci.go
  x/hard/alias.go
  x/hard/client/cli/query.go
  x/hard/client/cli/tx.go
  x/hard/client/rest/query.go
  x/hard/client/rest/rest.go
  x/hard/client/rest/tx.go
  x/hard/genesis.go
  x/hard/handler.go
  x/hard/keeper/borrow_test.go
  x/hard/keeper/claim.go
  x/hard/keeper/claim_test.go
  x/hard/keeper/deposit.go
  x/hard/keeper/deposit_test.go
  x/hard/keeper/hooks.go
  x/hard/keeper/interest_test.go
  x/hard/keeper/keeper.go
  x/hard/keeper/keeper_test.go
  x/hard/keeper/liquidation_test.go
  x/hard/keeper/params.go
  x/hard/keeper/querier.go
  x/hard/keeper/repay_test.go
  x/hard/keeper/rewards.go
  x/hard/keeper/rewards_test.go
  x/hard/keeper/timelock_test.go
  x/hard/simulation/decoder.go
  x/hard/simulation/decoder_test.go
  x/hard/types/claim.go
  x/hard/types/codec.go
  x/hard/types/expected_keepers.go
  x/hard/types/genesis.go
  x/hard/types/genesis_test.go
  x/hard/types/hooks.go
  x/hard/types/keys.go
  x/hard/types/params.go
  x/hard/types/params_test.go
  x/incentive/keeper/hooks.go
  x/incentive/types/expected_keepers.go
Labels: R4R

#775 Clean up leftover Hard module claim types/queries
  x/hard/alias.go
  x/hard/client/rest/query.go
  x/hard/client/rest/rest.go
  x/hard/client/rest/tx.go
  x/hard/types/codec.go
  x/hard/types/errors.go
  x/hard/types/events.go
  x/hard/types/msg.go
  x/hard/types/msg_test.go
  x/hard/types/params.go
  x/hard/types/querier.go
Labels: R4R

#776 Hard: Kava delegators earn HARD rewards via the Incentive module
  app/app.go
  x/hard/types/keys.go
  x/incentive/keeper/hooks.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/keeper_test.go
  x/incentive/keeper/params.go
  x/incentive/keeper/payout_test.go
  x/incentive/keeper/rewards.go
  x/incentive/keeper/rewards_test.go
  x/incentive/types/claims.go
  x/incentive/types/expected_keepers.go
Labels: R4R

#780 Incentive PR 4: claim Hard rewards via the Incentive module
  x/incentive/alias.go
  x/incentive/client/cli/query.go
  x/incentive/client/cli/tx.go
  x/incentive/client/rest/query.go
  x/incentive/client/rest/tx.go
  x/incentive/handler.go
  x/incentive/handler_test.go
  x/incentive/keeper/payout.go
  x/incentive/keeper/payout_test.go
  x/incentive/keeper/querier.go
  x/incentive/keeper/rewards.go
  x/incentive/types/codec.go
  x/incentive/types/events.go
  x/incentive/types/expected_keepers.go
  x/incentive/types/msg.go
  x/incentive/types/querier.go
Labels: R4R

#781 Query rewards via incentive module
  x/incentive/alias.go
  x/incentive/client/cli/query.go
  x/incentive/client/rest/query.go
  x/incentive/keeper/querier.go
  x/incentive/types/claims.go
  x/incentive/types/errors.go
  x/incentive/types/querier.go
Labels: R4R

#778 [R4R] fix: export harvest genesis state
  migrate/v0_11/migrate.go
  x/harvest/alias.go
  x/harvest/genesis.go
  x/harvest/keeper/claim_test.go
  x/harvest/keeper/deposit_test.go
  x/harvest/keeper/rewards_test.go
  x/harvest/keeper/timelock_test.go
  x/harvest/types/claim.go
  x/harvest/types/deposit.go
  x/harvest/types/genesis.go
  x/harvest/types/genesis_test.go
Labels: R4R

#782 Hard incentive reward querier updates for acceptance
  x/incentive/abci.go
  x/incentive/keeper/querier.go
  x/incentive/keeper/rewards.go
  x/incentive/keeper/rewards_test.go
Labels: R4R
